---
apiVersion: v3
kind: system
metadata:
  name: istio
  description: >
    Istio extends Kubernetes to establish a programmable, application-aware network using the powerful Envoy service proxy.
    Working with both Kubernetes and traditional workloads, Istio brings standard, universal traffic management, telemetry,
    and security to complex deployments.

  displayName: istio
  links:
    - name: docs.osinfra.io
      type: doc
      provider: Gitbook
      url: "https://docs.osinfra.io/product-guides/google-cloud-platform/kubernetes/istio"

    - name: google-cloud-kubernetes
      type: repo
      provider: Github
      url: "https://github.com/osinfra-io/google-cloud-kubernetes"

    - name: terraform-kubernetes-istio
      type: repo
      provider: Github
      url: "https://github.com/osinfra-io/terraform-kubernetes-istio"

  contacts:
    - type: email
      contact: platform-google-cloud-kubernetes@osinfra.io
    - type: google-chat
      contact: "https://mail.google.com/chat/u/0/#chat/space/AAAA1mERq4Q"

  owner: platform-google-cloud-kubernetes

spec:
  components:
    - service:istio-control-plane
    - service:istio-gateway
    - service:istio-test

datadog:
  performanceData:
    tags:
      - 'service:istio-control-plane'
      - 'service:istio-gateway'
      - 'service:istio-test'

  pipelines:
    fingerprints:
      - 0FQTEZZ2hCJC

---
apiVersion: v3
kind: service
metadata:
  name: istio-control-plane
  description: The control plane manages and configures proxies to route traffic.
  displayName: istio-control-plane
  inheritFrom: system:istio

spec:
  tier: Zero
  type: service
  languages:
    - go

datadog:
  performanceData:
    tags:
      - 'service:istio-control-plane'

---
apiVersion: v3
kind: service
metadata:
  name: istio-gateway
  description: The gateway describes a load balancer operating at the edge of the mesh receiving incoming or outgoing HTTP/TCP connections.
  displayName: istio-gateway
  inheritFrom: system:istio

  links:
    - name: sb.gcp.osinfra.io
      type: other
      url: "https://sb.gcp.osinfra.io"

    - name: us-east1-b.sb.gcp.osinfra.io
      type: other
      url: "https://us-east1-b.sb.gcp.osinfra.io"

    - name: us-east4-a.sb.gcp.osinfra.io
      type: other
      url: "https://us-east4-a.sb.gcp.osinfra.io"

    - name: nonprod.gcp.osinfra.io
      type: other
      url: "https://nonprod.gcp.osinfra.io"

    - name: us-east1-b.nonprod.gcp.osinfra.io
      type: other
      url: "https://us-east1-b.nonprod.gcp.osinfra.io"

    - name: us-east4-a.nonprod.gcp.osinfra.io
      type: other
      url: "https://us-east4-a.nonprod.gcp.osinfra.io"

    - name: gcp.osinfra.io
      type: other
      url: "https://gcp.osinfra.io"

    - name: us-east1-b.gcp.osinfra.io
      type: other
      url: "https://us-east1-b.gcp.osinfra.io"

    - name: us-east4-a.gcp.osinfra.io
      type: other
      url: "https://us-east4-a.gcp.osinfra.io"

spec:
  tier: Zero
  type: web
  languages:
    - cpp

datadog:
  performanceData:
    tags:
      - 'service:istio-gateway'

---
apiVersion: v3
kind: service
metadata:
  name: istio-test
  description: An example Istio test application that shows metadata about the Google Kubernetes Engine (GKE) cluster.
  displayName: istio-test

  links:
    - name: istio-test
      type: repo
      provider: Github
      url: "https://github.com/osinfra-io/istio-test"

    - name: sb.gcp.osinfra.io
      type: other
      url: "https://sb.gcp.osinfra.io/istio-test/health"

    - name: us-east1-b.sb.gcp.osinfra.io
      type: other
      url: "https://us-east1-b.sb.gcp.osinfra.io/istio-test/health"

    - name: us-east4-a.sb.gcp.osinfra.io
      type: other
      url: "https://us-east4-a.sb.gcp.osinfra.io/istio-test/health"

    - name: nonprod.gcp.osinfra.io
      type: other
      url: "https://nonprod.gcp.osinfra.io/istio-test/health"

    - name: us-east1-b.nonprod.gcp.osinfra.io
      type: other
      url: "https://us-east1-b.nonprod.gcp.osinfra.io/istio-test/health"

    - name: us-east4-a.nonprod.gcp.osinfra.io
      type: other
      url: "https://us-east4-a.nonprod.gcp.osinfra.io/istio-test/health"

    - name: gcp.osinfra.io
      type: other
      url: "https://gcp.osinfra.io/istio-test/health"

    - name: us-east1-b.gcp.osinfra.io
      type: other
      url: "https://us-east1-b.gcp.osinfra.io/istio-test/health"

    - name: us-east4-a.gcp.osinfra.io
      type: other
      url: "https://us-east4-a.gcp.osinfra.io/istio-test/health"

  contacts:
    - type: email
      contact: platform-google-cloud-kubernetes@osinfra.io
    - type: google-chat
      contact: "https://mail.google.com/chat/u/0/#chat/space/AAAA1mERq4Q"

  owner: platform-google-cloud-kubernetes

spec:
  lifecycle: production
  tier: zero
  type: web
  languages:
    - go

  dependsOn:
    - 'service:istio-gateway'

datadog:
  performanceData:
    tags:
      - 'service:istio-test'

  pipelines:
    fingerprints:
      - NabNkdMuNLxT

---
apiVersion: v3
kind: system
metadata:
  name: cert-manager
  description: >
    cert-manager is a powerful and extensible X.509 certificate controller for Kubernetes workloads.

  displayName: cert-manager
  links:
    - name: docs.osinfra.io
      type: doc
      provider: Gitbook
      url: "https://docs.osinfra.io/product-guides/google-cloud-platform/kubernetes/cert-manager"

    - name: google-cloud-kubernetes
      type: repo
      provider: Github
      url: "https://github.com/osinfra-io/google-cloud-kubernetes"

    - name: terraform-kubernetes-cert-manager
      type: repo
      provider: Github
      url: "https://github.com/osinfra-io/terraform-kubernetes-cert-manager"

  contacts:
    - type: email
      contact: platform-google-cloud-kubernetes@osinfra.io
    - type: google-chat
      contact: "https://mail.google.com/chat/u/0/#chat/space/AAAA1mERq4Q"

  owner: platform-google-cloud-kubernetes

spec:
  components:
    - service:cert-manager
    - service:cert-manager-cainjector
    - service:cert-manager-istio-csr
    - service:cert-manager-webhook

datadog:
  performanceData:
    tags:
      - 'service:cert-manager'
      - 'service:cert-manager-cainjector'
      - 'service:cert-manager-istio-csr'
      - 'service:cert-manager-webhook'

  pipelines:
    fingerprints:
      - 0FQTEZZ2hCJC

---
apiVersion: v3
kind: service
metadata:
  name: cert-manager
  description: This is the main service responsible for managing the lifecycle of certificates within your Kubernetes cluster.
  displayName: cert-manager
  inheritFrom: system:cert-manager

spec:
  tier: Zero
  type: service
  languages:
    - go

datadog:
  performanceData:
    tags:
      - 'service:cert-manager'

---
apiVersion: v3
kind: service
metadata:
  name: cert-manager-cainjector
  description: The CA (Certificate Authority) injector is responsible for injecting CA certificates into certain Kubernetes resources that need them, such as `ValidatingWebhookConfiguration`, `MutatingWebhookConfiguration`, and `APIServices`.
  displayName: cert-manager-cainjector
  inheritFrom: system:cert-manager

spec:
  tier: Zero
  type: service
  languages:
    - go

datadog:
  performanceData:
    tags:
      - 'service:cert-manager-cainjector'

---
apiVersion: v3
kind: service
metadata:
  name: cert-manager-istio-csr
  description: This service integrates cert-manager with Istio, specifically handling certificate signing requests (CSR) for workloads within Istio service mesh.
  displayName: cert-manager-istio-csr
  inheritFrom: system:cert-manager

spec:
  tier: Zero
  type: service
  languages:
    - go

datadog:
  performanceData:
    tags:
      - 'service:cert-manager-istio-csr'

---
apiVersion: v3
kind: service
metadata:
  name: cert-manager-webhook
  description: This service is responsible for handling webhook-based validation and mutation of cert-manager resources.
  displayName: cert-manager-webhook
  inheritFrom: system:cert-manager

spec:
  tier: Zero
  type: service
  languages:
    - go

datadog:
  performanceData:
    tags:
      - 'service:cert-manager-webhook'
