name: 🔩 Add or update shared VPC service projects
description: Service interface for adding or updating shared VPC service projects.
title: 🔩 Add or update shared VPC service projects
labels:
  - enhancement
  - good first issue

body:
  - type: input
    id: email-address
    attributes:
      label: "Email address:"
      description: How can we get in touch with you if we need more info?
      placeholder: user-name@osinfra.io
    validations:
      required: true

  - type: dropdown
    id: vpc-network
    attributes:
      label: "Select the VPC network:"
      options:
        - "standard-shared"
      multiple: true
    validations:
      required: true

  - type: textarea
    id: project-id
    attributes:
      label: "Shared VPC service project ID(s):"
      description: The shared VPC service project ID(s). When you use shared VPC, you designate a project as a host project and attach one or more other service projects to it.
      placeholder: "Example: stream-team-k8s-tf79a2-sb, stream-team-k8s-tf87df-pre-prod, stream-team-k8s-tf27rd-prod"
    validations:
      required: false

  - type: textarea
    id: comments
    attributes:
      label: "Additional comments:"
      description: Anything else you'd like to add that would help us understand your request better?
    validations:
      required: false
