environment                              = "non-production"
kubernetes_engine_master_ipv4_cidr_block = "10.63.240.80/28"
kubernetes_engine_node_location          = "us-east4-c"
kubernetes_engine_vpc_host_project_id    = "plt-lz-networking-tf81-nonprod"
region                                   = "us-east4"
remote_bucket                            = "plt-k8s-3bfe-nonprod"
zone                                     = "c"
