environment                              = "production"
kubernetes_engine_master_ipv4_cidr_block = "10.63.240.64/28"
kubernetes_engine_node_location          = "us-east4-b"
kubernetes_engine_vpc_host_project_id    = "plt-lz-networking-tfcb-prod"
region                                   = "us-east4"
remote_bucket                            = "plt-k8s-e194-prod"
zone                                     = "b"
