master_ipv4_cidr_block = "10.61.224.16/28"
region                 = "us-east4"
remote_bucket          = "plt-k8s-2c8b-sb"
vpc_host_project_id    = "plt-lz-networking-tfd8-sb"
zone                   = "c"
