environment            = "production"
master_ipv4_cidr_block = "10.63.240.64/28"
region                 = "us-east4"
remote_bucket          = "plt-k8s-e194-prod"
vpc_host_project_id    = "plt-lz-networking-tfcb-prod"
zone                   = "b"
