environment            = "non-production"
master_ipv4_cidr_block = "10.63.240.64/28"
node_location          = "us-east4-b"
region                 = "us-east4"
remote_bucket          = "plt-k8s-3bfe-nonprod"
vpc_host_project_id    = "plt-lz-networking-tf81-nonprod"
zone                   = "b"
