master_ipv4_cidr_block = "10.63.240.64/28"
node_location          = "us-east4-b"
region                 = "us-east4"
remote_bucket          = "plt-k8s-2c8b-sb"
vpc_host_project_id    = "plt-lz-networking-tfd8-sb"
zone                   = "b"
