name: Sandbox Destroy

on:
  workflow_dispatch:

# For reusable workflows, the permissions setting for id-token should be set to write at the
# caller workflow level or in the specific job that calls the reusable workflow.

permissions:
  id-token: write

jobs:
  us_east1_b_istio:
    name: "Istio: us-east1-b"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/plan-and-apply.yml@v0.2.4
    if: github.actor != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.ref }}
      environment: us-east1-b-sandbox
      github_environment: "Sandbox Istio: Regional - us-east1-b"
      service_account: plt-k8s-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_plan_args: -destroy -var-file=tfvars/us-east1-b-sandbox.tfvars
      terraform_state_bucket: plt-k8s-2c8b-sb
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: us-east1-b-istio-sandbox
      working_directory: regional/istio
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

  us_east4_a_istio:
    name: "Istio: us-east4-a"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/plan-and-apply.yml@v0.2.4
    if: github.actor != 'dependabot[bot]'
    with:
      checkout_ref: ${{ github.ref }}
      environment: us-east4-a-sandbox
      github_environment: "Sandbox Istio: Regional - us-east4-a"
      service_account: plt-k8s-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_plan_args: -destroy -var-file=tfvars/us-east4-a-sandbox.tfvars
      terraform_state_bucket: plt-k8s-2c8b-sb
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: us-east4-a-istio-sandbox
      working_directory: regional/istio
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

  us_east1_b_onboarding:
    name: "Onboarding: us-east1-b"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/plan-and-apply.yml@v0.2.4
    if: github.actor != 'dependabot[bot]'
    needs: us_east1_b_istio
    with:
      checkout_ref: ${{ github.ref }}
      environment: us-east1-b-sandbox
      github_environment: "Sandbox Onboarding: Regional - us-east1-b"
      service_account: plt-k8s-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_plan_args: -destroy -var-file=tfvars/us-east1-b-sandbox.tfvars -var-file=../../shared/tfvars/onboarding-sandbox.tfvars
      terraform_state_bucket: plt-k8s-2c8b-sb
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: us-east1-b-onboarding-sandbox
      working_directory: regional/onboarding
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

  us_east4_a_onboarding:
    name: "Onboarding: us-east4-a"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/plan-and-apply.yml@v0.2.4
    if: github.actor != 'dependabot[bot]'
    needs: us_east4_a_istio
    with:
      checkout_ref: ${{ github.ref }}
      environment: us-east4-a-sandbox
      github_environment: "Sandbox Onboarding: Regional - us-east4-a"
      service_account: plt-k8s-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_plan_args: -destroy -var-file=tfvars/us-east4-a-sandbox.tfvars -var-file=../../shared/tfvars/onboarding-sandbox.tfvars
      terraform_state_bucket: plt-k8s-2c8b-sb
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: us-east4-a-onboarding-sandbox
      working_directory: regional/onboarding
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

  us_east1_b_mci:
    name: "Multi-cluster Ingress: us-east1-b"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/plan-and-apply.yml@v0.2.4
    if: github.actor != 'dependabot[bot]'
    needs: us_east1_b_istio
    with:
      checkout_ref: ${{ github.ref }}
      environment: us-east1-b-sandbox
      github_environment: "Sandbox Multi-cluster Ingress: Regional - us-east1-a"
      service_account: plt-k8s-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_plan_args: -destroy -var-file=tfvars/us-east1-b-sandbox.tfvars
      terraform_state_bucket: plt-k8s-2c8b-sb
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: us-east1-b-mci-sandbox
      working_directory: regional/mci
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

  us_east4_a_mci:
    name: "Multi-cluster Ingress: us-east4-a"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/plan-and-apply.yml@v0.2.4
    if: github.actor != 'dependabot[bot]'
    needs: us_east4_a_istio
    with:
      checkout_ref: ${{ github.ref }}
      environment: us-east4-a-sandbox
      github_environment: "Sandbox Multi-cluster Ingress: Regional - us-east4-a"
      service_account: plt-k8s-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_plan_args: -destroy -var-file=tfvars/us-east4-a-sandbox.tfvars
      terraform_state_bucket: plt-k8s-2c8b-sb
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: us-east4-a-mci-sandbox
      working_directory: regional/mci
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

  us_east1_b:
    name: "Regional: us-east1-b"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/plan-and-apply.yml@v0.2.4
    if: github.actor != 'dependabot[bot]'
    needs: [us_east1_b_istio, us_east1_b_onboarding, us_east1_b_mci]
    with:
      checkout_ref: ${{ github.ref }}
      environment: us-east1-b-sandbox
      github_environment: "Sandbox: Regional - us-east1-b"
      service_account: plt-k8s-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_plan_args: -destroy -var-file=tfvars/us-east1-b-sandbox.tfvars
      terraform_state_bucket: plt-k8s-2c8b-sb
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: us-east1-b-sandbox
      working_directory: regional
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

  us_east4_a:
    name: "Regional: us-east4-a"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/plan-and-apply.yml@v0.2.4
    if: github.actor != 'dependabot[bot]'
    needs: [us_east4_a_istio, us_east4_a_onboarding, us_east4_a_mci]
    with:
      checkout_ref: ${{ github.ref }}
      environment: us-east4-a-sandbox
      github_environment: "Sandbox: Regional - us-east4-a"
      service_account: plt-k8s-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_plan_args: -destroy -var-file=tfvars/us-east4-a-sandbox.tfvars
      terraform_state_bucket: plt-k8s-2c8b-sb
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_workspace: us-east4-a-sandbox
      working_directory: regional
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}
